import { NavigationBar } from '@/components/admin/NavigationBar'
import '../globals.css'
import {Comfortaa} from "next/font/google";

const comfortaa = Comfortaa({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={comfortaa.className}>
        <NavigationBar />
        <div className='mx-auto max-w-[1440px] w-full p-6'>
          {children}
        </div>
      </body>
    </html>
  )
}
