export const categoryData = [
    {
        "categoryId": 1,
        "categoryName": "Landscape",
        "categoryImage": "https://images.unsplash.com/photo-1506260408121-e353d10b87c7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjR8fGxhbmRzY2FwZXxlbnwwfHwwfHx8MA%3D%3D",
        "categoryDescription": "Beautiful landscapes from around the world",
        "imageCount": 10,
        "images": [
            {
                "imageUrl": 'https://images.unsplash.com/34/BA1yLjNnQCI1yisIZGEi_2013-07-16_1922_IMG_9873.jpg?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGxhbmRzY2FwZXxlbnwwfHwwfHx8MA%3D%3D',
                "imageId": 1,
                "date": "2023-01-01",
                "location": "Mountains",
                "iso": 100,
                "shutterSpeed": "1/500",
                "aperture": "f/8",
                "whiteBalance": "Daylight",
                "exposure": 0,
                "focus": "Auto",
                "meteringMode": "Spot",
                "fileFormat": "JPEG",
                "resolution": "1920x1080"
            },
            {
                "imageId": 2,
                "imageUrl": 'https://images.unsplash.com/photo-1515404929826-76fff9fef6fe?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YmVhY2glMjBzdW5zZXR8ZW58MHx8MHx8fDA%3D',
                "date": "2023-02-15",
                "location": "Beach Sunset",
                "iso": 200,
                "shutterSpeed": "1/1000",
                "aperture": "f/4",
                "whiteBalance": "Warm",
                "exposure": -1,
                "focus": "Manual",
                "meteringMode": "Center-weighted",
                "fileFormat": "JPEG",
                "resolution": "2560x1440"
            },
            {
                "imageId": 3,
                "imageUrl": 'https://images.unsplash.com/photo-1542401886-65d6c61db217?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8ZGVzZXJ0fGVufDB8fDB8fHww',
                "date": "2023-03-20",
                "location": "Desert",
                "iso": 150,
                "shutterSpeed": "1/800",
                "aperture": "f/11",
                "whiteBalance": "Sunny",
                "exposure": 1,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "RAW",
                "resolution": "3000x2000"
            },
            {
                "imageId": 4,
                "imageUrl": 'https://images.unsplash.com/photo-1476231682828-37e571bc172f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Zm9yZXN0fGVufDB8fDB8fHww',
                "date": "2023-04-10",
                "location": "Forest",
                "iso": 400,
                "shutterSpeed": "1/200",
                "aperture": "f/5.6",
                "whiteBalance": "Daylight",
                "exposure": 0.5,
                "focus": "Auto",
                "meteringMode": "Spot",
                "fileFormat": "RAW",
                "resolution": "4000x3000"
            },
            {
                "imageId": 5,
                "imageUrl": 'https://images.unsplash.com/photo-1546882588-d9bd63f85a7e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8d2F0ZXJmYWxsfGVufDB8fDB8fHww',
                "date": "2023-05-05",
                "location": "Waterfall",
                "iso": 320,
                "shutterSpeed": "1/250",
                "aperture": "f/8",
                "whiteBalance": "Shade",
                "exposure": -0.5,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "JPEG",
                "resolution": "2500x1500"
            },
            {
                "imageId": 6,
                "imageUrl": 'https://images.unsplash.com/photo-1532953802613-6f66f1f4cc1b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fENPVU5UUllTSURFfGVufDB8fDB8fHww',
                "date": "2023-06-15",
                "location": "Countryside",
                "iso": 200,
                "shutterSpeed": "1/1000",
                "aperture": "f/4.5",
                "whiteBalance": "Cloudy",
                "exposure": 0,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "JPEG",
                "resolution": "2800x1600"
            },
            {
                "imageId": 7,
                "imageUrl":'https://images.unsplash.com/photo-1690900330615-10892d0e7dd7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Y2xpZnN8ZW58MHx8MHx8fDA%3D',
                "date": "2023-07-10",
                "location": "Cliffs",
                "iso": 180,
                "shutterSpeed": "1/800",
                "aperture": "f/10",
                "whiteBalance": "Daylight",
                "exposure": 1,
                "focus": "Manual",
                "meteringMode": "Center-weighted",
                "fileFormat": "RAW",
                "resolution": "3500x2000"
            },
            {
                "imageId": 8,
                "imageUrl": 'https://images.unsplash.com/photo-1590664216212-62e763768cae?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8dmFsbGV5fGVufDB8fDB8fHww',
                "date": "2023-08-22",
                "location": "Valley",
                "iso": 250,
                "shutterSpeed": "1/400",
                "aperture": "f/7.1",
                "whiteBalance": "Sunny",
                "exposure": -0.5,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "JPEG",
                "resolution": "3200x1800"
            },
            {
                "imageId": 9,
                "imageUrl": 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aXNsYW5kfGVufDB8fDB8fHww',
                "date": "2023-09-15",
                "location": "Island",
                "iso": 160,
                "shutterSpeed": "1/600",
                "aperture": "f/6.3",
                "whiteBalance": "Warm",
                "exposure": 0.5,
                "focus": "Auto",
                "meteringMode": "Spot",
                "fileFormat": "JPEG",
                "resolution": "2400x1200"
            },
            {
                "imageId": 10,
                "imageUrl": 'https://images.unsplash.com/photo-1492681290082-e932832941e6?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHN1bnJpc2V8ZW58MHx8MHx8fDA%3D',
                "date": "2023-10-10",
                "location": "Sunrise",
                "iso": 300,
                "shutterSpeed": "1/1200",
                "aperture": "f/5",
                "whiteBalance": "Daylight",
                "exposure": 0,
                "focus": "Manual",
                "meteringMode": "Center-weighted",
                "fileFormat": "RAW",
                "resolution": "3000x2500"
            }
        ]
    },
    {
        "categoryId": 2,
        "categoryName": "Wildlife",
        "categoryImage": "https://images.unsplash.com/photo-1518709594023-6eab9bab7b23?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHdpbGRsaWZlfGVufDB8fDB8fHww",
        "categoryDescription": "Fascinating wildlife in their natural habitats",
        "imageCount": 10,
        "images": [
            {
                "imageId": 11,
                "date": "2023-01-05",
                "location": "Savannah",
                "iso": 400,
                "shutterSpeed": "1/800",
                "aperture": "f/5.6",
                "whiteBalance": "Cloudy",
                "exposure": 1,
                "focus": "Continuous",
                "meteringMode": "Matrix",
                "fileFormat": "RAW",
                "resolution": "3000x2000"
            },
            {
                "imageId": 12,
                "date": "2023-02-12",
                "location": "Rainforest",
                "iso": 800,
                "shutterSpeed": "1/200",
                "aperture": "f/2.8",
                "whiteBalance": "Flash",
                "exposure": 2,
                "focus": "Single-point",
                "meteringMode": "Spot",
                "fileFormat": "RAW",
                "resolution": "4000x3000"
            },
            {
                "imageId": 13,
                "date": "2023-03-18",
                "location": "Arctic",
                "iso": 320,
                "shutterSpeed": "1/1000",
                "aperture": "f/4",
                "whiteBalance": "Daylight",
                "exposure": -1,
                "focus": "Auto",
                "meteringMode": "Spot",
                "fileFormat": "JPEG",
                "resolution": "2500x1500"
            },
            {
                "imageId": 14,
                "date": "2023-04-22",
                "location": "Desert",
                "iso": 500,
                "shutterSpeed": "1/500",
                "aperture": "f/8",
                "whiteBalance": "Sunny",
                "exposure": 0,
                "focus": "Manual",
                "meteringMode": "Matrix",
                "fileFormat": "JPEG",
                "resolution": "2800x1600"
            },
            {
                "imageId": 15,
                "date": "2023-05-10",
                "location": "Ocean",
                "iso": 200,
                "shutterSpeed": "1/1200",
                "aperture": "f/6.3",
                "whiteBalance": "Cloudy",
                "exposure": 0.5,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "RAW",
                "resolution": "3500x2000"
            },
            {
                "imageId": 16,
                "date": "2023-06-15",
                "location": "Jungle",
                "iso": 250,
                "shutterSpeed": "1/800",
                "aperture": "f/5",
                "whiteBalance": "Daylight",
                "exposure": -0.5,
                "focus": "Continuous",
                "meteringMode": "Spot",
                "fileFormat": "RAW",
                "resolution": "3200x1800"
            },
            {
                "imageId": 17,
                "date": "2023-07-10",
                "location": "Mountain",
                "iso": 180,
                "shutterSpeed": "1/1000",
                "aperture": "f/7.1",
                "whiteBalance": "Sunny",
                "exposure": 1,
                "focus": "Manual",
                "meteringMode": "Center-weighted",
                "fileFormat": "JPEG",
                "resolution": "2400x1200"
            },
            {
                "imageId": 18,
                "date": "2023-08-22",
                "location": "Swamp",
                "iso": 300,
                "shutterSpeed": "1/600",
                "aperture": "f/4.5",
                "whiteBalance": "Flash",
                "exposure": 0,
                "focus": "Auto",
                "meteringMode": "Spot",
                "fileFormat": "JPEG",
                "resolution": "3000x2500"
            },
            {
                "imageId": 19,
                "date": "2023-09-15",
                "location": "Grassland",
                "iso": 200,
                "shutterSpeed": "1/800",
                "aperture": "f/10",
                "whiteBalance": "Daylight",
                "exposure": 1,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "RAW",
                "resolution": "2500x2000"
            },
            {
                "imageId": 20,
                "date": "2023-10-10",
                "location": "Tundra",
                "iso": 400,
                "shutterSpeed": "1/500",
                "aperture": "f/5.6",
                "whiteBalance": "Cloudy",
                "exposure": -1,
                "focus": "Manual",
                "meteringMode": "Center-weighted",
                "fileFormat": "RAW",
                "resolution": "2800x2200"
            }
        ]
    },
    {
        "categoryId": 3,
        "categoryName": "Portrait",
        "categoryImage": "https://images.unsplash.com/photo-1566753323558-f4e0952af115?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHBvdHJhaXR8ZW58MHx8MHx8fDA%3D",
        "categoryDescription": "Capturing the essence of individuals",
        "imageCount": 10,
        "images": [
            {
                "imageId": 21,
                "date": "2023-01-15",
                "location": "Studio",
                "iso": 200,
                "shutterSpeed": "1/125",
                "aperture": "f/2.8",
                "whiteBalance": "Flash",
                "exposure": 1,
                "focus": "Continuous",
                "meteringMode": "Matrix",
                "fileFormat": "RAW",
                "resolution": "3000x2000"
            },
            {
                "imageId": 22,
                "date": "2023-02-20",
                "location": "Outdoor",
                "iso": 400,
                "shutterSpeed": "1/200",
                "aperture": "f/5.6",
                "whiteBalance": "Daylight",
                "exposure": 0.5,
                "focus": "Auto",
                "meteringMode": "Spot",
                "fileFormat": "JPEG",
                "resolution": "4000x3000"
            },
            {
                "imageId": 23,
                "date": "2023-03-25",
                "location": "Cityscape",
                "iso": 320,
                "shutterSpeed": "1/160",
                "aperture": "f/4",
                "whiteBalance": "Cloudy",
                "exposure": 0,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "RAW",
                "resolution": "2500x1500"
            },
            {
                "imageId": 24,
                "date": "2023-04-10",
                "location": "Park",
                "iso": 250,
                "shutterSpeed": "1/125",
                "aperture": "f/2.8",
                "whiteBalance": "Sunny",
                "exposure": -1,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "JPEG",
                "resolution": "2800x1600"
            },
            {
                "imageId": 25,
                "date": "2023-05-05",
                "location": "Beach",
                "iso": 200,
                "shutterSpeed": "1/250",
                "aperture": "f/4.5",
                "whiteBalance": "Daylight",
                "exposure": 0.5,
                "focus": "Continuous",
                "meteringMode": "Spot",
                "fileFormat": "RAW",
                "resolution": "3500x2000"
            },
            {
                "imageId": 26,
                "date": "2023-06-15",
                "location": "Countryside",
                "iso": 180,
                "shutterSpeed": "1/200",
                "aperture": "f/5.6",
                "whiteBalance": "Sunny",
                "exposure": 1,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "JPEG",
                "resolution": "3200x1800"
            },
            {
                "imageId": 27,
                "date": "2023-07-10",
                "location": "Garden",
                "iso": 300,
                "shutterSpeed": "1/160",
                "aperture": "f/4.5",
                "whiteBalance": "Cloudy",
                "exposure": -0.5,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "RAW",
                "resolution": "2400x1200"
            },
            {
                "imageId": 28,
                "date": "2023-08-22",
                "location": "Urban",
                "iso": 250,
                "shutterSpeed": "1/125",
                "aperture": "f/2.8",
                "whiteBalance": "Flash",
                "exposure": 1,
                "focus": "Continuous",
                "meteringMode": "Matrix",
                "fileFormat": "JPEG",
                "resolution": "3000x2500"
            },
            {
                "imageId": 29,
                "date": "2023-09-15",
                "location": "Vintage",
                "iso": 200,
                "shutterSpeed": "1/200",
                "aperture": "f/5.6",
                "whiteBalance": "Daylight",
                "exposure": -1,
                "focus": "Auto",
                "meteringMode": "Spot",
                "fileFormat": "JPEG",
                "resolution": "2500x2000"
            },
            {
                "imageId": 30,
                "date": "2023-10-10",
                "location": "Rural",
                "iso": 180,
                "shutterSpeed": "1/160",
                "aperture": "f/4",
                "whiteBalance": "Sunny",
                "exposure": 0.5,
                "focus": "Manual",
                "meteringMode": "Center-weighted",
                "fileFormat": "RAW",
                "resolution": "2800x2200"
            }
        ]
    },
    {
        "categoryId": 4,
        "categoryName": "Architecture",
        "categoryImage": "https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8YXJjaGl0ZWN0dXJlfGVufDB8fDB8fHww",
        "categoryDescription": "Structures and buildings around the world",
        "imageCount": 10,
        "images": [
            {
                "imageId": 31,
                "date": "2023-01-10",
                "location": "City Skyline",
                "iso": 200,
                "shutterSpeed": "1/250",
                "aperture": "f/8",
                "whiteBalance": "Daylight",
                "exposure": 0,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "JPEG",
                "resolution": "3000x2000"
            },
            {
                "imageId": 32,
                "date": "2023-02-15",
                "location": "Modern Office",
                "iso": 400,
                "shutterSpeed": "1/200",
                "aperture": "f/5.6",
                "whiteBalance": "Sunny",
                "exposure": 0.5,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "RAW",
                "resolution": "4000x3000"
            },
            {
                "imageId": 33,
                "date": "2023-03-20",
                "location": "Historical Building",
                "iso": 320,
                "shutterSpeed": "1/160",
                "aperture": "f/4",
                "whiteBalance": "Cloudy",
                "exposure": -1,
                "focus": "Auto",
                "meteringMode": "Spot",
                "fileFormat": "JPEG",
                "resolution": "2500x1500"
            },
            {
                "imageId": 34,
                "date": "2023-04-10",
                "location": "Skyscraper",
                "iso": 250,
                "shutterSpeed": "1/125",
                "aperture": "f/2.8",
                "whiteBalance": "Daylight",
                "exposure": 1,
                "focus": "Continuous",
                "meteringMode": "Matrix",
                "fileFormat": "RAW",
                "resolution": "2800x1600"
            },
            {
                "imageId": 35,
                "date": "2023-05-05",
                "location": "Bridge",
                "iso": 200,
                "shutterSpeed": "1/250",
                "aperture": "f/4.5",
                "whiteBalance": "Sunny",
                "exposure": -0.5,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "JPEG",
                "resolution": "3500x2000"
            },
            {
                "imageId": 36,
                "date": "2023-06-15",
                "location": "Museum",
                "iso": 180,
                "shutterSpeed": "1/200",
                "aperture": "f/5.6",
                "whiteBalance": "Cloudy",
                "exposure": 0,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "JPEG",
                "resolution": "3200x1800"
            },
            {
                "imageId": 37,
                "date": "2023-07-10",
                "location": "Church",
                "iso": 300,
                "shutterSpeed": "1/160",
                "aperture": "f/4.5",
                "whiteBalance": "Sunny",
                "exposure": 1,
                "focus": "Continuous",
                "meteringMode": "Spot",
                "fileFormat": "RAW",
                "resolution": "2400x1200"
            },
            {
                "imageId": 38,
                "date": "2023-08-22",
                "location": "Government Building",
                "iso": 250,
                "shutterSpeed": "1/125",
                "aperture": "f/2.8",
                "whiteBalance": "Daylight",
                "exposure": 0,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "JPEG",
                "resolution": "3000x2500"
            },
            {
                "imageId": 39,
                "date": "2023-09-15",
                "location": "Library",
                "iso": 200,
                "shutterSpeed": "1/200",
                "aperture": "f/5.6",
                "whiteBalance": "Cloudy",
                "exposure": -1,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "RAW",
                "resolution": "2500x2000"
            },
            {
                "imageId": 40,
                "date": "2023-10-10",
                "location": "Residential Complex",
                "iso": 180,
                "shutterSpeed": "1/160",
                "aperture": "f/4",
                "whiteBalance": "Sunny",
                "exposure": 0.5,
                "focus": "Auto",
                "meteringMode": "Center-weighted",
                "fileFormat": "RAW",
                "resolution": "2800x2200"
            }
        ]
    },
    {
        "categoryId": 5,
        "categoryName": "Street Photography",
        "categoryImage": "https://images.unsplash.com/photo-1539651044670-315229da9d2f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHN0cmVldHxlbnwwfHwwfHx8MA%3D%3D",
        "categoryDescription": "Capturing the essence of everyday life on the streets",
        "imageCount": 10,
        "images": [
            {
                "imageId": 41,
                "date": "2023-01-10",
                "location": "Busy City Center",
                "iso": 200,
                "shutterSpeed": "1/250",
                "aperture": "f/4",
                "whiteBalance": "Daylight",
                "exposure": 0,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "JPEG",
                "resolution": "3000x2000"
            },
            {
                "imageId": 42,
                "date": "2023-02-15",
                "location": "Marketplace",
                "iso": 400,
                "shutterSpeed": "1/200",
                "aperture": "f/5.6",
                "whiteBalance": "Sunny",
                "exposure": 0.5,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "RAW",
                "resolution": "4000x3000"
            },
            {
                "imageId": 43,
                "date": "2023-03-20",
                "location": "Subway Station",
                "iso": 320,
                "shutterSpeed": "1/160",
                "aperture": "f/2.8",
                "whiteBalance": "Cloudy",
                "exposure": -1,
                "focus": "Auto",
                "meteringMode": "Spot",
                "fileFormat": "JPEG",
                "resolution": "2500x1500"
            },
            {
                "imageId": 44,
                "date": "2023-04-10",
                "location": "Street Performer",
                "iso": 250,
                "shutterSpeed": "1/125",
                "aperture": "f/4.5",
                "whiteBalance": "Daylight",
                "exposure": 1,
                "focus": "Continuous",
                "meteringMode": "Matrix",
                "fileFormat": "RAW",
                "resolution": "2800x1600"
            },
            {
                "imageId": 45,
                "date": "2023-05-05",
                "location": "Pedestrian Zone",
                "iso": 200,
                "shutterSpeed": "1/250",
                "aperture": "f/5.6",
                "whiteBalance": "Sunny",
                "exposure": -0.5,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "JPEG",
                "resolution": "3500x2000"
            },
            {
                "imageId": 46,
                "date": "2023-06-15",
                "location": "Street Cafe",
                "iso": 180,
                "shutterSpeed": "1/200",
                "aperture": "f/4.5",
                "whiteBalance": "Sunny",
                "exposure": 0,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "JPEG",
                "resolution": "3200x1800"
            },
            {
                "imageId": 47,
                "date": "2023-07-10",
                "location": "City Square",
                "iso": 300,
                "shutterSpeed": "1/160",
                "aperture": "f/4.5",
                "whiteBalance": "Sunny",
                "exposure": 1,
                "focus": "Continuous",
                "meteringMode": "Spot",
                "fileFormat": "RAW",
                "resolution": "2400x1200"
            },
            {
                "imageId": 48,
                "date": "2023-08-22",
                "location": "Street Art",
                "iso": 250,
                "shutterSpeed": "1/125",
                "aperture": "f/2.8",
                "whiteBalance": "Daylight",
                "exposure": 0,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "JPEG",
                "resolution": "3000x2500"
            },
            {
                "imageId": 49,
                "date": "2023-09-15",
                "location": "City Life",
                "iso": 200,
                "shutterSpeed": "1/200",
                "aperture": "f/5.6",
                "whiteBalance": "Cloudy",
                "exposure": -1,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "RAW",
                "resolution": "2500x2000"
            },
            {
                "imageId": 50,
                "date": "2023-10-10",
                "location": "Street Vendor",
                "iso": 180,
                "shutterSpeed": "1/160",
                "aperture": "f/4",
                "whiteBalance": "Sunny",
                "exposure": 0.5,
                "focus": "Auto",
                "meteringMode": "Center-weighted",
                "fileFormat": "RAW",
                "resolution": "2800x2200"
            }
        ]
    },
    {
        "categoryId": 6,
        "categoryName": "Macro Photography",
        "categoryImage": "https://images.unsplash.com/photo-1527942364978-2b826fc00de6?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjR8fG1hY3JvfGVufDB8fDB8fHww",
        "categoryDescription": "Close-up shots revealing intricate details",
        "imageCount": 10,
        "images": [
            {
                "imageId": 51,
                "date": "2023-01-10",
                "subject": "Flower Petal",
                "iso": 100,
                "shutterSpeed": "1/200",
                "aperture": "f/2.8",
                "whiteBalance": "Daylight",
                "exposure": 0,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "JPEG",
                "resolution": "3000x2000"
            },
            {
                "imageId": 52,
                "date": "2023-02-15",
                "subject": "Insect Eyes",
                "iso": 200,
                "shutterSpeed": "1/250",
                "aperture": "f/4",
                "whiteBalance": "Sunny",
                "exposure": -0.5,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "RAW",
                "resolution": "4000x3000"
            },
            {
                "imageId": 53,
                "date": "2023-03-20",
                "subject": "Dew Drops on Leaf",
                "iso": 150,
                "shutterSpeed": "1/160",
                "aperture": "f/5.6",
                "whiteBalance": "Cloudy",
                "exposure": 1,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "JPEG",
                "resolution": "2500x1500"
            },
            {
                "imageId": 54,
                "date": "2023-04-10",
                "subject": "Butterfly Wing Scales",
                "iso": 200,
                "shutterSpeed": "1/125",
                "aperture": "f/2.8",
                "whiteBalance": "Daylight",
                "exposure": -1,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "RAW",
                "resolution": "2800x1600"
            },
            {
                "imageId": 55,
                "date": "2023-05-05",
                "subject": "Spider Web",
                "iso": 100,
                "shutterSpeed": "1/250",
                "aperture": "f/4.5",
                "whiteBalance": "Sunny",
                "exposure": 0.5,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "JPEG",
                "resolution": "3500x2000"
            },
            {
                "imageId": 56,
                "date": "2023-06-15",
                "subject": "Ant Carrying Food",
                "iso": 150,
                "shutterSpeed": "1/200",
                "aperture": "f/5.6",
                "whiteBalance": "Sunny",
                "exposure": 0,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "JPEG",
                "resolution": "3200x1800"
            },
            {
                "imageId": 57,
                "date": "2023-07-10",
                "subject": "Water Droplet on Blade of Grass",
                "iso": 100,
                "shutterSpeed": "1/160",
                "aperture": "f/4.5",
                "whiteBalance": "Daylight",
                "exposure": 1,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "RAW",
                "resolution": "2400x1200"
            },
            {
                "imageId": 58,
                "date": "2023-08-22",
                "subject": "Caterpillar on Leaf",
                "iso": 150,
                "shutterSpeed": "1/125",
                "aperture": "f/2.8",
                "whiteBalance": "Sunny",
                "exposure": -0.5,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "RAW",
                "resolution": "3000x2500"
            },
            {
                "imageId": 59,
                "date": "2023-09-15",
                "subject": "Mushroom Cap",
                "iso": 100,
                "shutterSpeed": "1/200",
                "aperture": "f/5.6",
                "whiteBalance": "Cloudy",
                "exposure": 1,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "JPEG",
                "resolution": "2500x2000"
            },
            {
                "imageId": 60,
                "date": "2023-10-10",
                "subject": "Snail on Stone",
                "iso": 150,
                "shutterSpeed": "1/160",
                "aperture": "f/4",
                "whiteBalance": "Daylight",
                "exposure": 0.5,
                "focus": "Auto",
                "meteringMode": "Center-weighted",
                "fileFormat": "RAW",
                "resolution": "2800x2200"
            }
        ]
    },
    {
        "categoryId": 7,
        "categoryName": "Fashion Photography",
        "categoryImage": "https://images.unsplash.com/photo-1612381197160-04a7c68c06cc?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8ZmFzaG9pbnxlbnwwfHwwfHx8MA%3D%3D",
        "categoryDescription": "Elegance and style in the world of fashion",
        "imageCount": 10,
        "images": [
            {
                "imageId": 61,
                "date": "2023-01-10",
                "model": "Sophia Johnson",
                "iso": 100,
                "shutterSpeed": "1/200",
                "aperture": "f/2.8",
                "whiteBalance": "Daylight",
                "exposure": 0,
                "pose": "Casual",
                "outfit": "Streetwear",
                "fileFormat": "JPEG",
                "resolution": "3000x2000"
            },
            {
                "imageId": 62,
                "date": "2023-02-15",
                "model": "Ethan Miller",
                "iso": 200,
                "shutterSpeed": "1/250",
                "aperture": "f/4",
                "whiteBalance": "Sunny",
                "exposure": -0.5,
                "pose": "Formal",
                "outfit": "Suit",
                "fileFormat": "RAW",
                "resolution": "4000x3000"
            },
            {
                "imageId": 63,
                "date": "2023-03-20",
                "model": "Isabella Thompson",
                "iso": 150,
                "shutterSpeed": "1/160",
                "aperture": "f/5.6",
                "whiteBalance": "Cloudy",
                "exposure": 1,
                "pose": "Casual",
                "outfit": "Boho-Chic",
                "fileFormat": "JPEG",
                "resolution": "2500x1500"
            },
            {
                "imageId": 64,
                "date": "2023-04-10",
                "model": "Noah Davis",
                "iso": 200,
                "shutterSpeed": "1/125",
                "aperture": "f/2.8",
                "whiteBalance": "Daylight",
                "exposure": -1,
                "pose": "Fashion-forward",
                "outfit": "Designer Dress",
                "fileFormat": "RAW",
                "resolution": "2800x1600"
            },
            {
                "imageId": 65,
                "date": "2023-05-05",
                "model": "Olivia White",
                "iso": 100,
                "shutterSpeed": "1/250",
                "aperture": "f/4.5",
                "whiteBalance": "Sunny",
                "exposure": 0.5,
                "pose": "Casual",
                "outfit": "Summer Vibes",
                "fileFormat": "JPEG",
                "resolution": "3500x2000"
            },
            {
                "imageId": 66,
                "date": "2023-06-15",
                "model": "Mason Lee",
                "iso": 150,
                "shutterSpeed": "1/200",
                "aperture": "f/5.6",
                "whiteBalance": "Sunny",
                "exposure": 0,
                "pose": "Formal",
                "outfit": "Tuxedo",
                "fileFormat": "JPEG",
                "resolution": "3200x1800"
            },
            {
                "imageId": 67,
                "date": "2023-07-10",
                "model": "Ava Martinez",
                "iso": 100,
                "shutterSpeed": "1/160",
                "aperture": "f/4.5",
                "whiteBalance": "Daylight",
                "exposure": 1,
                "pose": "Casual",
                "outfit": "Vintage",
                "fileFormat": "RAW",
                "resolution": "2400x1200"
            },
            {
                "imageId": 68,
                "date": "2023-08-22",
                "model": "Elijah Robinson",
                "iso": 150,
                "shutterSpeed": "1/125",
                "aperture": "f/2.8",
                "whiteBalance": "Sunny",
                "exposure": -0.5,
                "pose": "Fashion-forward",
                "outfit": "Street Style",
                "fileFormat": "RAW",
                "resolution": "3000x2500"
            },
            {
                "imageId": 69,
                "date": "2023-09-15",
                "model": "Amelia Garcia",
                "iso": 100,
                "shutterSpeed": "1/200",
                "aperture": "f/5.6",
                "whiteBalance": "Cloudy",
                "exposure": 1,
                "pose": "Casual",
                "outfit": "Denim Collection",
                "fileFormat": "JPEG",
                "resolution": "2500x2000"
            },
            {
                "imageId": 70,
                "date": "2023-10-10",
                "model": "Logan Taylor",
                "iso": 150,
                "shutterSpeed": "1/160",
                "aperture": "f/4",
                "whiteBalance": "Daylight",
                "exposure": 0.5,
                "pose": "Casual",
                "outfit": "Sporty Chic",
                "fileFormat": "RAW",
                "resolution": "2800x2200"
            }
        ]
    },
    {
        "categoryId": 8,
        "categoryName": "Travel Photography",
        "categoryImage": "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8dHJhdmVsfGVufDB8fDB8fHww",
        "categoryDescription": "Exploring the beauty of diverse landscapes and cultures",
        "imageCount": 10,
        "images": [
            {
                "imageId": 71,
                "date": "2023-01-10",
                "location": "Santorini, Greece",
                "iso": 100,
                "shutterSpeed": "1/200",
                "aperture": "f/2.8",
                "whiteBalance": "Daylight",
                "exposure": 0,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "JPEG",
                "resolution": "3000x2000"
            },
            {
                "imageId": 72,
                "date": "2023-02-15",
                "location": "Kyoto, Japan",
                "iso": 200,
                "shutterSpeed": "1/250",
                "aperture": "f/4",
                "whiteBalance": "Sunny",
                "exposure": -0.5,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "RAW",
                "resolution": "4000x3000"
            },
            {
                "imageId": 73,
                "date": "2023-03-20",
                "location": "Marrakech, Morocco",
                "iso": 150,
                "shutterSpeed": "1/160",
                "aperture": "f/5.6",
                "whiteBalance": "Cloudy",
                "exposure": 1,
                "focus": "Auto",
                "meteringMode": "Spot",
                "fileFormat": "JPEG",
                "resolution": "2500x1500"
            },
            {
                "imageId": 74,
                "date": "2023-04-10",
                "location": "Grand Canyon, USA",
                "iso": 200,
                "shutterSpeed": "1/125",
                "aperture": "f/2.8",
                "whiteBalance": "Daylight",
                "exposure": -1,
                "focus": "Continuous",
                "meteringMode": "Matrix",
                "fileFormat": "RAW",
                "resolution": "2800x1600"
            },
            {
                "imageId": 75,
                "date": "2023-05-05",
                "location": "Venice, Italy",
                "iso": 100,
                "shutterSpeed": "1/250",
                "aperture": "f/4.5",
                "whiteBalance": "Sunny",
                "exposure": 0.5,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "JPEG",
                "resolution": "3500x2000"
            },
            {
                "imageId": 76,
                "date": "2023-06-15",
                "location": "Patagonia, Argentina",
                "iso": 150,
                "shutterSpeed": "1/200",
                "aperture": "f/5.6",
                "whiteBalance": "Sunny",
                "exposure": 0,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "JPEG",
                "resolution": "3200x1800"
            },
            {
                "imageId": 77,
                "date": "2023-07-10",
                "location": "Cappadocia, Turkey",
                "iso": 100,
                "shutterSpeed": "1/160",
                "aperture": "f/4.5",
                "whiteBalance": "Daylight",
                "exposure": 1,
                "focus": "Continuous",
                "meteringMode": "Spot",
                "fileFormat": "RAW",
                "resolution": "2400x1200"
            },
            {
                "imageId": 78,
                "date": "2023-08-22",
                "location": "Banff National Park, Canada",
                "iso": 150,
                "shutterSpeed": "1/125",
                "aperture": "f/2.8",
                "whiteBalance": "Sunny",
                "exposure": -0.5,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "JPEG",
                "resolution": "3000x2500"
            },
            {
                "imageId": 79,
                "date": "2023-09-15",
                "location": "Great Wall of China",
                "iso": 100,
                "shutterSpeed": "1/200",
                "aperture": "f/5.6",
                "whiteBalance": "Cloudy",
                "exposure": 1,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "RAW",
                "resolution": "2500x2000"
            },
            {
                "imageId": 80,
                "date": "2023-10-10",
                "location": "Aoraki / Mount Cook, New Zealand",
                "iso": 150,
                "shutterSpeed": "1/160",
                "aperture": "f/4",
                "whiteBalance": "Daylight",
                "exposure": 0.5,
                "focus": "Auto",
                "meteringMode": "Center-weighted",
                "fileFormat": "RAW",
                "resolution": "2800x2200"
            }
        ]
    },
    {
        "categoryId": 9,
        "categoryName": "Sports Photography",
        "categoryImage": "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHNwb3J0c3xlbnwwfHwwfHx8MA%3D%3D",
        "categoryDescription": "Action-packed moments in various sports",
        "imageCount": 10,
        "images": [
            {
                "imageId": 81,
                "date": "2023-01-10",
                "sport": "Soccer",
                "iso": 200,
                "shutterSpeed": "1/500",
                "aperture": "f/2.8",
                "whiteBalance": "Daylight",
                "exposure": 0,
                "location": "Stadium",
                "action": "Goal Celebration",
                "fileFormat": "JPEG",
                "resolution": "3000x2000"
            },
            {
                "imageId": 82,
                "date": "2023-02-15",
                "sport": "Basketball",
                "iso": 400,
                "shutterSpeed": "1/1000",
                "aperture": "f/4",
                "whiteBalance": "Sunny",
                "exposure": 0.5,
                "location": "Indoor Arena",
                "action": "Dunk",
                "fileFormat": "RAW",
                "resolution": "4000x3000"
            },
            {
                "imageId": 83,
                "date": "2023-03-20",
                "sport": "Tennis",
                "iso": 320,
                "shutterSpeed": "1/800",
                "aperture": "f/5.6",
                "whiteBalance": "Cloudy",
                "exposure": -1,
                "location": "Court",
                "action": "Serve",
                "fileFormat": "JPEG",
                "resolution": "2500x1500"
            },
            {
                "imageId": 84,
                "date": "2023-04-10",
                "sport": "Swimming",
                "iso": 250,
                "shutterSpeed": "1/500",
                "aperture": "f/2.8",
                "whiteBalance": "Daylight",
                "exposure": 1,
                "location": "Pool",
                "action": "Butterfly Stroke",
                "fileFormat": "RAW",
                "resolution": "2800x1600"
            },
            {
                "imageId": 85,
                "date": "2023-05-05",
                "sport": "Golf",
                "iso": 200,
                "shutterSpeed": "1/1000",
                "aperture": "f/4.5",
                "whiteBalance": "Sunny",
                "exposure": -0.5,
                "location": "Golf Course",
                "action": "Swing",
                "fileFormat": "JPEG",
                "resolution": "3500x2000"
            },
            {
                "imageId": 86,
                "date": "2023-06-15",
                "sport": "Athletics",
                "iso": 180,
                "shutterSpeed": "1/800",
                "aperture": "f/5.6",
                "whiteBalance": "Sunny",
                "exposure": 0,
                "location": "Track and Field",
                "action": "100m Sprint",
                "fileFormat": "JPEG",
                "resolution": "3200x1800"
            },
            {
                "imageId": 87,
                "date": "2023-07-10",
                "sport": "Baseball",
                "iso": 300,
                "shutterSpeed": "1/500",
                "aperture": "f/4.5",
                "whiteBalance": "Sunny",
                "exposure": 1,
                "location": "Baseball Field",
                "action": "Pitch",
                "fileFormat": "RAW",
                "resolution": "2400x1200"
            },
            {
                "imageId": 88,
                "date": "2023-08-22",
                "sport": "Cycling",
                "iso": 250,
                "shutterSpeed": "1/1000",
                "aperture": "f/2.8",
                "whiteBalance": "Daylight",
                "exposure": 0,
                "location": "Road Race",
                "action": "Sprint Finish",
                "fileFormat": "JPEG",
                "resolution": "3000x2500"
            },
            {
                "imageId": 89,
                "date": "2023-09-15",
                "sport": "Snowboarding",
                "iso": 200,
                "shutterSpeed": "1/800",
                "aperture": "f/5.6",
                "whiteBalance": "Cloudy",
                "exposure": -1,
                "location": "Mountain Slope",
                "action": "Jump",
                "fileFormat": "RAW",
                "resolution": "2500x2000"
            },
            {
                "imageId": 90,
                "date": "2023-10-10",
                "sport": "Cricket",
                "iso": 180,
                "shutterSpeed": "1/1000",
                "aperture": "f/4",
                "whiteBalance": "Sunny",
                "exposure": 0.5,
                "location": "Cricket Ground",
                "action": "Batsman in Action",
                "fileFormat": "RAW",
                "resolution": "2800x2200"
            }
        ]
    },
    {
        "categoryId": 10,
        "categoryName": "Night Photography",
        "categoryImage": "https://images.unsplash.com/photo-1488866022504-f2584929ca5f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bmlnaHR8ZW58MHx8MHx8fDA%3D",
        "categoryDescription": "Capturing the beauty of the night with long exposures",
        "imageCount": 10,
        "images": [
            {
                "imageId": 91,
                "date": "2023-01-10",
                "location": "City Skyline",
                "iso": 200,
                "shutterSpeed": "30s",
                "aperture": "f/2.8",
                "whiteBalance": "Tungsten",
                "exposure": 0,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "JPEG",
                "resolution": "3000x2000"
            },
            {
                "imageId": 92,
                "date": "2023-02-15",
                "location": "Urban Street",
                "iso": 400,
                "shutterSpeed": "20s",
                "aperture": "f/4",
                "whiteBalance": "Street Light",
                "exposure": 0.5,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "RAW",
                "resolution": "4000x3000"
            },
            {
                "imageId": 93,
                "date": "2023-03-20",
                "location": "Historic Landmark",
                "iso": 320,
                "shutterSpeed": "25s",
                "aperture": "f/5.6",
                "whiteBalance": "Incandescent",
                "exposure": -1,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "JPEG",
                "resolution": "2500x1500"
            },
            {
                "imageId": 94,
                "date": "2023-04-10",
                "location": "Night Market",
                "iso": 250,
                "shutterSpeed": "15s",
                "aperture": "f/2.8",
                "whiteBalance": "Fluorescent",
                "exposure": 1,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "RAW",
                "resolution": "2800x1600"
            },
            {
                "imageId": 95,
                "date": "2023-05-05",
                "location": "Waterfront",
                "iso": 200,
                "shutterSpeed": "20s",
                "aperture": "f/4.5",
                "whiteBalance": "Moonlight",
                "exposure": -0.5,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "JPEG",
                "resolution": "3500x2000"
            },
            {
                "imageId": 96,
                "date": "2023-06-15",
                "location": "Bridge",
                "iso": 150,
                "shutterSpeed": "25s",
                "aperture": "f/5.6",
                "whiteBalance": "City Lights",
                "exposure": 0,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "JPEG",
                "resolution": "3200x1800"
            },
            {
                "imageId": 97,
                "date": "2023-07-10",
                "location": "Starry Sky",
                "iso": 100,
                "shutterSpeed": "30s",
                "aperture": "f/4.5",
                "whiteBalance": "Daylight",
                "exposure": 1,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "RAW",
                "resolution": "2400x1200"
            },
            {
                "imageId": 98,
                "date": "2023-08-22",
                "location": "Neon Lights",
                "iso": 150,
                "shutterSpeed": "15s",
                "aperture": "f/2.8",
                "whiteBalance": "Neon",
                "exposure": -0.5,
                "focus": "Auto",
                "meteringMode": "Matrix",
                "fileFormat": "JPEG",
                "resolution": "3000x2500"
            },
            {
                "imageId": 99,
                "date": "2023-09-15",
                "location": "Festival Fireworks",
                "iso": 100,
                "shutterSpeed": "20s",
                "aperture": "f/5.6",
                "whiteBalance": "Firelight",
                "exposure": 1,
                "focus": "Manual",
                "meteringMode": "Spot",
                "fileFormat": "RAW",
                "resolution": "2500x2000"
            },
            {
                "imageId": 100,
                "date": "2023-10-10",
                "location": "Countryside Observatory",
                "iso": 150,
                "shutterSpeed": "25s",
                "aperture": "f/4",
                "whiteBalance": "Starlight",
                "exposure": 0.5,
                "focus": "Auto",
                "meteringMode": "Center-weighted",
                "fileFormat": "RAW",
                "resolution": "2800x2200"
            }
        ]
    }
]
