import {RegisterData} from "@/components/types";

export const REGISTER_INITIAL_DATA: RegisterData = {
    country: '',
    countryCode: '',
    passportNumber: '',
    email: '',
    cardType: '',
    cardNumber: '',
    monthYear: '',
    cvv: '',
    cardCountry: '',
    zipCode: '',
    ticketNumber: '',
    flightNumber: '',
    takeOffFrom: '',
    takeOffTime: '',
    landingTo: '',
    landingTime: ''
}

export const TASK_INITIAL_DATA = {
    date: '',
    time: '',
    userId: '',
    taskId: '',
    categoryId: '',
    photo: []
}

export const TOUR_PLAN_INITIAL_DATA = {
    day01Location: '',
    day01Hotel: '',
    day01Activity: '',
    day02Location: '',
    day02Hotel: '',
    day02Activity: '',
    day03Location: '',
    day03Hotel: '',
    day03Activity: '',
    day04Location: '',
    day04Hotel: '',
    day04Activity: '',
    day05Location: '',
    day05Hotel: '',
    day05Activity: '',
    day06Location: '',
    day06Hotel: '',
    day06Activity: '',
    day07Location: '',
    day07Hotel: '',
    day07Activity: '',
    day08Location: '',
    day08Hotel: '',
    day08Activity: '',
    day09Location: '',
    day09Hotel: '',
    day09Activity: '',
    day10Location: '',
    day10Hotel: '',
    day10Activity: '',
    day11Location: '',
    day11Hotel: '',
    day11Activity: '',
    day12Location: '',
    day12Hotel: '',
    day12Activity: '',
    day13Location: '',
    day13Hotel: '',
    day13Activity: '',
    day14Location: '',
    day14Hotel: '',
    day14Activity: '',
    day15Location: '',
    day15Hotel: '',
    day15Activity: '',
    day16Location: '',
    day16Hotel: '',
    day16Activity: '',
    day17Location: '',
    day17Hotel: '',
    day17Activity: '',
    day18Location: '',
    day18Hotel: '',
    day18Activity: '',
    day19Location: '',
    day19Hotel: '',
    day19Activity: '',
    day20Location: '',
    day20Hotel: '',
    day20Activity: '',
}